### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Kellyontheboat**
鄭克萱
http://52.68.255.89:8000/

### CODE REVIEW

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by Kellyontheboat** [comment]
鄭克萱
http://52.68.255.89:8000/
http://52.68.255.89:8000/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Font size for normal text is too large.

Next time, you should merge approved pull request first, and open another pull request for another task.

**Comment by Kellyontheboat** [comment]
好的 修正完畢
http://52.68.255.89:8000/
http://52.68.255.89:8000/attraction/10

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
