### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Kellyontheboat**
鄭克萱
http://52.68.255.89:8000/
http://52.68.255.89:8000/attraction/10
http://52.68.255.89:8000/booking
嘗試使用複數購物車，所以窄版面上的垃圾桶有調整位置

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your pages always call User Auth API multiple times. 1 time User Auth API call is enough to meet requirements.

**Comment by Kellyontheboat** [comment]
修正完成

**Review by cwpeng — CHANGES_REQUESTED** [review]
Link on 預定行程 is broken.

**Comment by Kellyontheboat** [comment]
修正完成

**Review by cwpeng — APPROVED** [review]
OK. Done.

Additional issue: your total price does not update after deleting.

**Comment by Kellyontheboat** [comment]
yes,it needs to reload the page to update the total price,i will fix that part.

**Pull request merged**
